site_name: Post Event Messaging Info
theme: readthedocs
pages:
  - Home: index.md
  - NHS Standard Contract Guidance: StandardContractExtract2015.md
  - Configuration Guides:
    - Configuring ITK for GP Systems: guides/configuring_gp_systems.md
  - Frequently Asked Questions:
    - Operational Questions: operational_faq.md
    - Technical Questions: technical_faq.md
  - Glossary: glossary.md
  - Want To Help?: contribute.md
